const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

const memberNames = [
  "Abdul Rahman", "Ahmad Syarif H", "Aliyadi", "M. Zikril Isril", "Sumardin",
  "Chairil Anwar", "Khoirol", "Bakrim Bere", "M. Mukarrom", "Ansori",
  "Iwan", "Bung Seng", "AngTonio", "Basrah", "Jono",
  "Hariyanto", "Tutas Wahyu", "Erwin", "Indal Desri Putra", "Daniesl Samosir",
  "Suhairi", "Rio", "Yanto", "Ardi Yent", "Qiu Ran",
  "Sung Tiam", "Usman Syamnai", "Riska Triafani", "Rifqi Mangihuttua Hasibuan", "Hengki",
  "Erni Harjayanti", "Andre Soemantrei", "Taufik Hidayat", "Lela Wirdyanti", "Putri Adliana Hasibuan",
  "Roshamidah", "Melanie", "Diko Pahlevi Alfatoni", "Hamdi", "Parjo Nurgiyanto",
  "Heri", "Sudarwadi", "Bambang Sutejo", "Nur Hasidah", "Anugrah Candra",
  "Marwan", "Sandi Parulian",
];

const memberPositions = ["Ketua DPC", "Wakil Ketua", "Sekretaris", "Bendahara", "Koordinator Lapangan", "Koordinator Pelatihan", "Bidang Humas", "Bidang Keanggotaan"];
const memberPhotos = ["/member-dummy-1.jpeg", "/member-dummy-2.jpeg", "/member-dummy-3.jpeg", "/uploads/1784221305257-f652719a-d758-47ae-ae59-a9beca92924e.jpg"];

async function main() {
  const email = process.env.ADMIN_EMAIL || "admin@hpibintan.org";
  const password = process.env.ADMIN_PASSWORD || "AdminHPI2026!";
  await prisma.admin.upsert({ where: { email }, update: {}, create: { email, password: await bcrypt.hash(password, 12), name: "Admin HPI Bintan" } });
  await prisma.organizationProfile.upsert({ where: { id: "main" }, update: { heroTitle: "Himpunan Pramuwisata Indonesia DPC Kabupaten Bintan", history: "DPC HPI Kabupaten Bintan adalah Dewan Pimpinan Cabang Himpunan Pramuwisata Indonesia yang berperan sebagai wadah profesi pramuwisata di Kabupaten Bintan. Kami mengawal profesionalisme, etika pelayanan, peningkatan kompetensi, dan kolaborasi pariwisata daerah.", vision: "Menjadi organisasi profesi pramuwisata yang profesional, kompeten, beretika, dan menjadi rujukan utama pelayanan wisata Kabupaten Bintan dan Kepulauan Riau.", mission: "Meningkatkan kompetensi anggota melalui pelatihan berkala, membangun jaringan kemitraan, mendukung promosi destinasi, dan memastikan layanan pramuwisata yang aman, informatif, serta berkesan.", heroSubtitle: "Dewan Pimpinan Cabang Himpunan Pramuwisata Indonesia Kabupaten Bintan - mengawal profesionalisme dan memajukan pariwisata Kepulauan Riau." }, create: { id: "main", heroTitle: "Himpunan Pramuwisata Indonesia DPC Kabupaten Bintan", history: "DPC HPI Kabupaten Bintan adalah Dewan Pimpinan Cabang Himpunan Pramuwisata Indonesia yang berperan sebagai wadah profesi pramuwisata di Kabupaten Bintan. Kami mengawal profesionalisme, etika pelayanan, peningkatan kompetensi, dan kolaborasi pariwisata daerah.", vision: "Menjadi organisasi profesi pramuwisata yang profesional, kompeten, beretika, dan menjadi rujukan utama pelayanan wisata Kabupaten Bintan dan Kepulauan Riau.", mission: "Meningkatkan kompetensi anggota melalui pelatihan berkala, membangun jaringan kemitraan, mendukung promosi destinasi, dan memastikan layanan pramuwisata yang aman, informatif, serta berkesan.", structure: "Ketua, Wakil Ketua, Sekretaris, Bendahara, Koordinator Lapangan, Bidang Pendidikan, Bidang Humas, dan Koordinator Mitra.", heroSubtitle: "Dewan Pimpinan Cabang Himpunan Pramuwisata Indonesia Kabupaten Bintan - mengawal profesionalisme dan memajukan pariwisata Kepulauan Riau." } });
  await prisma.contact.upsert({ where: { id: "main" }, update: { address: "Jl. Langsat RT.001 / RW.001, Desa Sebong Lagoi, Kec. Teluk Sebong, Kab. Bintan.", email: "info@hpibintan.org", whatsapp: "+62 812 7565 7026", mapUrl: "https://maps.google.com/?q=Jl.%20Langsat%20Desa%20Sebong%20Lagoi%20Teluk%20Sebong%20Bintan" }, create: { id: "main", address: "Jl. Langsat RT.001 / RW.001, Desa Sebong Lagoi, Kec. Teluk Sebong, Kab. Bintan.", email: "info@hpibintan.org", whatsapp: "+62 812 7565 7026", mapUrl: "https://maps.google.com/?q=Jl.%20Langsat%20Desa%20Sebong%20Lagoi%20Teluk%20Sebong%20Bintan" } });
  if ((await prisma.member.count()) === 0) await prisma.member.createMany({ data: memberNames.map((name, index) => ({ name, position: memberPositions[index] || "Pramuwisata", contact: `+62 812-4500-11${String(index + 1).padStart(2, "0")}`, photo: memberPhotos[index % memberPhotos.length], isActive: true })) });
  if ((await prisma.announcement.count()) === 0) await prisma.announcement.createMany({ data: [{ title: "Pelatihan Guide Nasional 2026", content: "HPI Bintan membuka pendaftaran pelatihan peningkatan kompetensi pramuwisata untuk standar pelayanan destinasi internasional.", isPublished: true }, { title: "Rapat Bulanan Pengurus dan Anggota", content: "Rapat koordinasi bulanan membahas agenda kegiatan, pelayanan wisata, dan program kerja lintas bidang.", isPublished: true }, { title: "Workshop Pariwisata Berkelanjutan", content: "Kegiatan kolaboratif bersama mitra destinasi untuk memperkuat narasi wisata alam, budaya, dan hospitality Bintan.", isPublished: true }] });
  if ((await prisma.gallery.count()) === 0) await prisma.gallery.createMany({ data: [["Kegiatan Rapat Pengurus", "PHOTO", "/foto-rapat/rapat-01.jpeg"], ["Rapat Koordinasi Anggota", "PHOTO", "/foto-rapat/rapat-02.jpeg"], ["Dokumentasi Rapat Bulanan", "PHOTO", "/foto-rapat/rapat-03.jpeg"], ["Suasana Rapat HPI Bintan", "PHOTO", "/foto-rapat/rapat-04.jpeg"], ["Seminar Hospitality", "PHOTO", "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=85"]].map(([title, category, fileUrl]) => ({ title, category, fileUrl, description: "Dokumentasi kegiatan HPI Bintan." })) });
  if ((await prisma.documentation.count()) === 0) await prisma.documentation.createMany({ data: [["Dokumentasi Rapat Pengurus", "/foto-rapat/rapat-05.jpeg", "JPG"], ["Album Rapat Anggota", "/foto-rapat/rapat-06.jpeg", "JPG"], ["AD/ART HPI Bintan", "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=85", "PDF"], ["Surat Keputusan Kepengurusan", "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=85", "PDF"], ["Program Kerja Tahunan", "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=85", "PDF"]].map(([title, fileUrl, fileType]) => ({ title, fileUrl, fileType, description: "Dokumen dan dokumentasi organisasi yang dapat diperbarui melalui dashboard admin." })) });
  if ((await prisma.transportation.count()) === 0) await prisma.transportation.createMany({ data: [["Toyota Hiace Premio", "Van Premium", 12, "AVAILABLE", "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80"], ["Toyota Hiace Commuter", "Van Wisata", 14, "AVAILABLE", "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?auto=format&fit=crop&w=1200&q=80"], ["Toyota Innova Zenix", "MPV", 6, "AVAILABLE", "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80"], ["Toyota Alphard", "Executive MPV", 5, "UNAVAILABLE", "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80"], ["Bus Pariwisata", "Bus", 32, "AVAILABLE", "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=1200&q=80"], ["Speed Boat", "Transportasi Laut", 10, "AVAILABLE", "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1200&q=80"]].map(([name, vehicleType, capacity, status, photo]) => ({ name, vehicleType, capacity, status, photo, description: "Unit layanan transportasi mitra untuk kebutuhan perjalanan wisata dan kegiatan organisasi." })) });
  if ((await prisma.meeting.count()) === 0) await prisma.meeting.createMany({ data: [{ title: "Agenda Sertifikasi Kompetensi", date: new Date("2026-08-12"), time: "09.00 WIB", location: "Bintan Tourism Center", description: "Koordinasi persiapan sertifikasi dan kurasi peserta." }, { title: "Forum Mitra Pariwisata", date: new Date("2026-08-24"), time: "14.00 WIB", location: "Lagoi Bay", description: "Pertemuan dengan mitra transportasi, hotel, dan destinasi." }, { title: "Rapat Program Kerja Triwulan", date: new Date("2026-09-05"), time: "10.00 WIB", location: "Sekretariat HPI Bintan", description: "Evaluasi program dan penyusunan agenda lanjutan." }] });
  const destinations = [
    { category: "Wisata Pantai", name: "Lagoi Bay", description: "Kawasan pantai premium dengan promenade, resort, dan aktivitas keluarga.", location: "Lagoi, Bintan", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Lagoi+Bay+Bintan" },
    { category: "Wisata Pantai", name: "Pantai Trikora", description: "Pantai ikonik dengan bebatuan granit dan suasana pesisir yang alami.", location: "Trikora, Bintan Timur", image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Pantai+Trikora+Bintan" },
    { category: "Wisata Pantai", name: "Pantai Sakera", description: "Ruang publik pesisir untuk bersantai, kuliner, dan menikmati matahari terbenam.", location: "Tanjung Uban", image: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Pantai+Sakera+Bintan" },
    { category: "Wisata Alam", name: "Treasure Bay", description: "Laguna air laut buatan terbesar dengan pengalaman rekreasi air modern.", location: "Lagoi", image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Treasure+Bay+Bintan" },
    { category: "Wisata Alam", name: "Gurun Pasir Busung", description: "Bentang pasir eksotis bekas tambang yang menjadi spot foto favorit wisatawan.", location: "Busung", image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Gurun+Pasir+Busung+Bintan" },
    { category: "Wisata Alam", name: "Danau Biru Busung", description: "Danau berwarna biru terang yang kontras dengan lanskap pasir putih.", location: "Busung", image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Danau+Biru+Busung+Bintan" },
    { category: "Wisata Alam", name: "Bintan Mangrove", description: "Ekowisata sungai mangrove dengan interpretasi alam dan konservasi.", location: "Sebong Lagoi", image: "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Bintan+Mangrove" },
    { category: "Wisata Alam", name: "Safari Lagoi & Eco Farm", description: "Area edukasi satwa dan pertanian ramah keluarga di kawasan wisata Bintan.", location: "Lagoi", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Safari+Lagoi+Eco+Farm" },
    { category: "Wisata Sejarah & Budaya", name: "Pulau Penyengat", description: "Pulau bersejarah pusat warisan Melayu, religi, dan literasi kawasan Riau.", location: "Tanjungpinang", image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Pulau+Penyengat" },
    { category: "Wisata Sejarah & Budaya", name: "Vihara Ksitigarbha Bodhisattva", description: "Destinasi religi dan budaya dengan deretan patung yang monumental.", location: "Tanjungpinang", image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Vihara+Ksitigarbha+Bodhisattva" },
    { category: "Wisata Sejarah & Budaya", name: "Museum Sultan Sulaiman Badrul Alamsyah", description: "Museum kota yang menyimpan kisah sejarah, budaya, dan identitas Melayu Riau.", location: "Tanjungpinang", image: "https://images.unsplash.com/photo-1566127992631-137a642a90f4?auto=format&fit=crop&w=1200&q=80", mapUrl: "https://www.google.com/maps/search/?api=1&query=Museum+Sultan+Sulaiman+Badrul+Alamsyah" }
  ];
  const cms = {
    active_members: "127", transportation_units: "38", documentation_count: "56", activities_count: "112", partners_count: "15", gallery_count: "24", videos_count: "8",
    hero_image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2400&q=90", map_image: "/peta-pulau-bintan.jpg", map_text: "Pulau Bintan berada pada jalur strategis pariwisata Kepulauan Riau. HPI Bintan mendukung layanan interpretasi destinasi untuk wilayah pesisir, kawasan resort, ekowisata, sejarah, dan budaya.",
    destinations: JSON.stringify(destinations), partners: JSON.stringify(["Dinas Pariwisata", "Pelaku Hotel", "Mitra Transportasi", "Komunitas Wisata", "Desa Wisata", "Travel Agent"])
  };
  for (const [key, value] of Object.entries(cms)) await prisma.settings.upsert({ where: { key }, update: { value }, create: { key, value } });
}

main().finally(() => prisma.$disconnect());
