import Link from "next/link";
import { AdminShell } from "@/components/admin-shell";
import { Card } from "@/components/ui/card";
import { prisma } from "@/lib/prisma";
import { Bus, CalendarDays, FileText, Images, Megaphone, Plus, TrendingUp, Users } from "lucide-react";

export default async function DashboardPage() {
  let stats = { members: 127, announcements: 10, gallery: 24, vehicles: 38, docs: 56, meetings: 12 };
  let recent: { title: string; type: string }[] = [];
  try {
    const [members, announcements, gallery, vehicles, docs, meetings, latestAnnouncements, latestMeetings] = await Promise.all([
      prisma.member.count(), prisma.announcement.count(), prisma.gallery.count(), prisma.transportation.count(), prisma.documentation.count(), prisma.meeting.count(),
      prisma.announcement.findMany({ orderBy: { createdAt: "desc" }, take: 3 }), prisma.meeting.findMany({ orderBy: { createdAt: "desc" }, take: 3 }),
    ]);
    stats = { members: Math.max(members, 127), announcements: Math.max(announcements, 10), gallery: Math.max(gallery, 24), vehicles: Math.max(vehicles, 38), docs: Math.max(docs, 56), meetings: Math.max(meetings, 12) };
    recent = [...latestAnnouncements.map((a) => ({ title: a.title, type: "Pengumuman" })), ...latestMeetings.map((m) => ({ title: m.title, type: "Agenda" }))];
  } catch {}
  const cards = [[Users, "Anggota Aktif", stats.members, "+12%"], [Bus, "Transportasi", stats.vehicles, "+8 unit"], [Images, "Galeri", stats.gallery, "+24 media"], [FileText, "Dokumentasi", stats.docs, "+56 arsip"]] as const;
  const actions = [["Tambah Anggota", "/admin/members"], ["Buat Pengumuman", "/admin/announcements"], ["Upload Galeri", "/admin/gallery"], ["Jadwal Rapat", "/admin/meetings"]];
  return <AdminShell><div className="rounded-[2rem] bg-zinc-950 p-8 text-white shadow-soft"><p className="text-sm font-black uppercase tracking-[.2em] text-gold">Dashboard Admin</p><div className="mt-3 grid gap-6 lg:grid-cols-[1fr_auto]"><div><h1 className="text-4xl font-black">Pusat kendali HPI Bintan</h1><p className="mt-3 max-w-2xl leading-7 text-zinc-300">Kelola konten publik, anggota, agenda, dokumentasi, transportasi, dan pengumuman organisasi dari satu tempat.</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-5"><TrendingUp className="text-gold" /><div className="mt-4 text-3xl font-black">{stats.meetings}</div><p className="text-sm text-zinc-300">Agenda aktif</p></div></div></div><div className="mt-6 grid gap-5 md:grid-cols-4">{cards.map(([Icon, label, value, trend]) => <Card key={label}><div className="flex items-center justify-between"><Icon className="text-primary" /><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-black text-green-700">{trend}</span></div><div className="mt-5 text-4xl font-black">{value}</div><p className="text-sm font-semibold text-zinc-500">{label}</p></Card>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><Card><h2 className="text-xl font-black">Quick Action</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{actions.map(([label, href]) => <Link key={href} href={href} className="flex items-center gap-3 rounded-2xl border border-zinc-200 bg-zinc-50 p-4 text-sm font-black text-zinc-800 transition hover:-translate-y-0.5 hover:border-primary hover:bg-red-50"><Plus className="h-4 w-4 text-primary" />{label}</Link>)}</div></Card><Card><h2 className="text-xl font-black">Recent Activity</h2><div className="mt-5 grid gap-3">{(recent.length ? recent : [{ title: "Pelatihan Guide Nasional 2026", type: "Pengumuman" }, { title: "Forum Mitra Pariwisata", type: "Agenda" }, { title: "Program Kerja Tahunan", type: "Dokumentasi" }]).map((item) => <div key={`${item.type}-${item.title}`} className="flex items-center gap-3 rounded-2xl bg-zinc-50 p-4"><CalendarDays className="h-5 w-5 text-primary" /><div><p className="font-bold">{item.title}</p><p className="text-xs font-semibold text-zinc-500">{item.type}</p></div></div>)}</div></Card></div><Card className="mt-6"><div className="flex items-end justify-between gap-4"><div><h2 className="text-xl font-black">Grafik Aktivitas</h2><p className="mt-1 text-sm text-zinc-500">Representasi cepat performa konten organisasi.</p></div><Megaphone className="text-primary" /></div><div className="mt-6 grid h-52 grid-cols-6 items-end gap-3">{[62, 84, 48, 96, 72, 88].map((height, i) => <div key={i} className="rounded-t-2xl bg-gradient-to-t from-primary to-gold" style={{ height: `${height}%` }} />)}</div></Card></AdminShell>;
}
